name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    #https://github.com/actions/first-interaction
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome Vikas on creating this first issue' first issue"
        pr-message: "Welcome Vikas on creating this PR ' first pull request"
